# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_provider.appsco:
        class: AppBundle\Security\User\AppscoUserProvider
        arguments:
            - @store

    store:
        class: AppBundle\Services\Store
        arguments:
            - @serializer
            - %kernel.root_dir%/../var/files

    loader:
        class: AppBundle\Services\Loader
        arguments:
            - @jms_translation.loader_manager

    project_creator:
        class: AppBundle\Services\ProjectCreator
        arguments:
            - @store

    file_adder:
        class: AppBundle\Services\FileAdder
        arguments:
            - @store
            - @loader
            - @jms_translation.loader_manager
            - @jms_translation.file_writer
